USE PASTEBOOK_NJDD
GO
DROP DATABASE PASTEBOOK_NJDD

--DROP TABLE PB_REF_COUNTRY
CREATE TABLE PB_REF_COUNTRY(
ID INT IDENTITY (1,1) PRIMARY KEY,
COUNTRY VARCHAR(50) UNIQUE NOT NULL
)

--DROP TABLE PB_USER
CREATE TABLE PB_USER(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
[USER_NAME] VARCHAR(50) UNIQUE NOT NULL,
[PASSWORD] VARCHAR(50) NOT NULL,
[SALT] VARCHAR(100) NOT NULL,
[FIRST_NAME] VARCHAR(50) NOT NULL,
[LAST_NAME] VARCHAR(50) NOT NULL,
[BIRTHDAY] DATE NOT NULL,
[COUNTRY_ID] INT FOREIGN KEY REFERENCES PB_REF_COUNTRY(ID),
MOBILE_NO VARCHAR(50),
GENDER CHAR(1) NOT NULL,
PROFILE_PIC VARBINARY(MAX),
DATE_CREATED DATE NOT NULL,
ABOUT_ME VARCHAR(2000),
EMAIL_ADDRESS VARCHAR(50) UNIQUE NOT NULL
)

--DROP TABLE PB_FRIEND
CREATE TABLE PB_FRIEND(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,  
[USER_ID] INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL,
FRIEND_ID INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL,
REQUEST CHAR(1) NOT NULL,
BLOCKED CHAR(1) NOT NULL,
CREATED_DATE DATETIME NOT NULL,
CONSTRAINT UQ_PB_FRIEND UNIQUE([USER_ID], FRIEND_ID)
)

--DROP TABLE PB_POST
CREATE TABLE PB_POST(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
CREATED_DATE DATETIME NOT NULL,
CONTENT VARCHAR(1000) NOT NULL,
PROFILE_OWNER_ID INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL,
POSTER_ID INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL
)

--DROP TABLE PB_COMMENT
CREATE TABLE PB_COMMENT(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
POST_ID INT FOREIGN KEY REFERENCES PB_POST(ID) NOT NULL,
POSTER_ID INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL,
CONTENT VARCHAR(1000) NOT NULL,
DATE_CREATED DATETIME NOT NULL
)

--DROP TABLE PB_LIKE
CREATE TABLE PB_LIKE(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
POST_ID INT FOREIGN KEY REFERENCES PB_POST(ID) NOT NULL,
LIKED_BY INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL
)

--DROP TABLE PB_NOTIFICATION
CREATE TABLE PB_NOTIFICATION(
ID INT IDENTITY (1,1) PRIMARY KEY,
RECEIVER_ID INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL,
NOTIF_TYPE CHAR(1) NOT NULL,
SENDER_ID INT FOREIGN KEY REFERENCES PB_USER(ID) NOT NULL,
CREATED_DATE DATETIME NOT NULL,
COMMENT_ID INT FOREIGN KEY REFERENCES PB_COMMENT(ID),
POST_ID INT FOREIGN KEY REFERENCES PB_POST(ID),
SEEN VARCHAR(1)
)